platform: linux
image_resource:
  type: docker-image
  source:
    repository: sk8s/kafka-zookeeper

inputs:
- name: git-topic-controller
- name: git-pfs-ci
- name: sk8s-version

outputs:
- name: docker-context

run:
  path: /bin/bash
  args:
  - -o
  - pipefail
  - -exc
  - |

    build_root=$(pwd)

    source "$build_root/git-pfs-ci/tasks/scripts/common.sh"
    SK8S_VERSION=$(determine_sk8s_version "$build_root/git-topic-controller" "$build_root/sk8s-version")

    export GOPATH=$(go env GOPATH)

    mkdir -p "$GOPATH/src/github.com/sk8sio"
    cp -pr git-topic-controller "$GOPATH/src/github.com/sk8sio/topic-controller"

    pushd "$GOPATH/src/github.com/sk8sio/topic-controller/"

      make test

      make build-for-docker

      ls -lath

      cp -pr . "$build_root/docker-context/"

      echo "$SK8S_VERSION" > "$build_root/docker-context/sk8s_version"

    popd
