#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

start_docker

mkdir -p ~/.kube
echo "$KUBECONFIG_STRING" > ~/.kube/config

build_root="$PWD"
mkdir -p "$GOPATH/src/github.com/pivotal-cf"
cp -r "$build_root/git-faas-cli" "$GOPATH/src/github.com/pivotal-cf/faas-cli"

cd "$GOPATH/src/github.com/pivotal-cf/faas-cli"

./build.sh
cp ./faas-cli* "$build_root/faas-cli-out/"