#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

invoker_version=$(cat invoker-version/version)
cli_version=$(cat cli-version/version)

echo
echo "Building sample $SAMPLE_PATH"
echo "Using invoker version $invoker_version"
echo "Using CLI version $cli_version"
echo

echo "Installing riff locally"
install cli-binary/riff-linux-amd64-$cli_version /usr/local/bin/riff

pushd git-riff/"$SAMPLE_PATH"
  echo "Running riff init in $PWD"
  riff init "$SAMPLE_LANGUAGE" \
    --artifact "$SAMPLE_ARTIFACT" \
    --useraccount "$DOCKER_TEST_ORG" \
    --riff-version $invoker_version # Actually used for the tag on the base image.
  
  echo "$PWD after riff init:"
  ls -alh

  echo
  echo "Dockerfile contents:"
  echo
  cat Dockerfile
  echo
popd

echo "Copying init'd sample to output directory"
cp -rf git-riff/"$SAMPLE_PATH"/* riff-init-output/

echo
echo Done.
echo
