#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

source /opt/resource/common.sh
start_docker

docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"

build_root=$(pwd)

EXISTING_VERSION=$(head $build_root/source-semver/version)
TAG_VERSION=$(echo $EXISTING_VERSION | awk -F'-' '{print $1}')

echo "Tagging [${DOCKER_IMAGE}:${EXISTING_VERSION}] as [${DOCKER_IMAGE}:${TAG_VERSION}]"

docker pull "${DOCKERHUB_ORG_SOURCE}/${DOCKER_IMAGE}:${EXISTING_VERSION}"

IMAGE_ID=$(docker images "$DOCKERHUB_ORG_SOURCE/$DOCKER_IMAGE" --format {{.ID}})

docker tag "$IMAGE_ID" "$DOCKERHUB_ORG_TARGET/$DOCKER_IMAGE:$TAG_VERSION"

docker push "${DOCKERHUB_ORG_TARGET}/${DOCKER_IMAGE}:${TAG_VERSION}"
